# Generated by Django 5.2 on 2025-04-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='documents_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
