# Generated by Django 5.2 on 2025-04-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_scheme_documents_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='benefits',
        ),
        migrations.AddField(
            model_name='scheme',
            name='age_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='benefit_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='caste',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='differently_abled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='ministry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='minority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='documents_required',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility_criteria',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
