# Generated by Django 5.2 on 2025-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_remove_scheme_benefits_scheme_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='benefit_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='documents_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
